apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gsmct-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: home.gsmct.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gsmct-service
            port:
              number: 80
