-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS address_t CASCADE;
DROP TABLE IF EXISTS assoc_details_t CASCADE;
DROP TABLE IF EXISTS assoc_type_t CASCADE;
DROP TABLE IF EXISTS homeowner_t CASCADE;
DROP TABLE IF EXISTS board_member_type_t CASCADE;
DROP TABLE IF EXISTS unit_t CASCADE;
DROP TABLE IF EXISTS address_type_t CASCADE;
DROP TABLE IF EXISTS user_t CASCADE;
DROP TABLE IF EXISTS user_role_t CASCADE;
DROP TABLE IF EXISTS role_t CASCADE;

CREATE TABLE IF NOT EXISTS assoc_details_t
(
    assoc_id integer NOT NULL,
    assoc_name character varying(100) NOT NULL,
    address_id integer,
    assoc_type_id integer,
    CONSTRAINT assoc_details_t_pk1 PRIMARY KEY (assoc_id, assoc_name),
    CONSTRAINT assoc_name_uk UNIQUE (assoc_name),
    CONSTRAINT assoc_id_uk UNIQUE (assoc_id)
);

CREATE TABLE IF NOT EXISTS assoc_type_t
(
    assoc_type_id integer NOT NULL,
    assoc_type_desc character varying(500) NOT NULL,
    CONSTRAINT assoc_type_pk1 PRIMARY KEY (assoc_type_id, assoc_type_desc),
    CONSTRAINT assoc_type_id_uk UNIQUE (assoc_type_id)
);

CREATE TABLE IF NOT EXISTS homeowner_t
(
    howner_id integer NOT NULL,
    address_id integer,
    unit_id integer,
    first_name character varying(100) NOT NULL,
    middle_name character varying(100),
    last_name character varying(100) NOT NULL,
    phone_number character varying(12),
    mobile_number character varying(12),
    member_type character varying(1),
    mem_term_start date,
    mem_term_end date,
    CONSTRAINT homeowner_t_pk1 PRIMARY KEY (howner_id)
);

CREATE TABLE IF NOT EXISTS address_t
(
    address_id integer NOT NULL,
    address_type character varying(1) NOT NULL,
    street character varying(100),
    town character varying(100),
    state character varying(100),
    zip_code integer,
    country character varying(100) DEFAULT 'United States of America',
    CONSTRAINT address_t_pk1 PRIMARY KEY (address_id)
);

CREATE TABLE IF NOT EXISTS address_type_t
(
    address_type character varying(1) NOT NULL,
    address_description character varying(100),
    CONSTRAINT address_type_t_pk1 PRIMARY KEY (address_type)
);

CREATE TABLE IF NOT EXISTS board_member_type_t
(
    member_type character varying(1) NOT NULL,
    member_description character varying(100),
    CONSTRAINT board_member_type_t_pk1 PRIMARY KEY (member_type)
);

CREATE TABLE IF NOT EXISTS unit_t
(
    unit_id integer NOT NULL,
    address_id integer,
    assoc_id integer,
    CONSTRAINT unit_t_pk1 PRIMARY KEY (unit_id)
);

CREATE TABLE IF NOT EXISTS role_t
(
    role_id integer NOT NULL,
    role_description character varying(100),
    CONSTRAINT role_t_pk1 PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS user_role_t
(
    user_id integer NOT NULL,
    role_id integer NOT NULL,
    description character varying(100)
);

CREATE TABLE IF NOT EXISTS user_t
(
    user_id integer NOT NULL,
    user_name character varying(100) NOT NULL,
    user_password character varying(100) NOT NULL,
    CONSTRAINT user_t_pk1 PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS assoc_details_t
    ADD CONSTRAINT address_id_fk FOREIGN KEY (address_id)
    REFERENCES address_t (address_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS assoc_details_t
    ADD CONSTRAINT assoc_type_id_fk FOREIGN KEY (assoc_type_id)
    REFERENCES assoc_type_t (assoc_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS homeowner_t
    ADD CONSTRAINT "Address_id_fk" FOREIGN KEY (address_id)
    REFERENCES address_t (address_id) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS homeowner_t
    ADD CONSTRAINT member_type_fk FOREIGN KEY (member_type)
    REFERENCES board_member_type_t (member_type) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS homeowner_t
    ADD CONSTRAINT unit_id_fk FOREIGN KEY (unit_id)
    REFERENCES unit_t (unit_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS address_t
    ADD CONSTRAINT "Address_type_fk" FOREIGN KEY (address_type)
    REFERENCES address_type_t (address_type) MATCH SIMPLE
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS unit_t
    ADD CONSTRAINT address_id_fk FOREIGN KEY (address_id)
    REFERENCES address_t (address_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS unit_t
    ADD CONSTRAINT assoc_id_fk FOREIGN KEY (assoc_id)
    REFERENCES assoc_details_t (assoc_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS user_role_t
    ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id)
    REFERENCES user_t (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS user_role_t
    ADD CONSTRAINT role_id_fk FOREIGN KEY (role_id)
    REFERENCES role_t (role_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS user_t
    ADD CONSTRAINT user_id_fk FOREIGN KEY (user_id)
    REFERENCES homeowner_t (howner_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;

