apiVersion: apps/v1
kind: Deployment
metadata:
  name: gsmct-deployment
  labels:
    app: gsmctdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gsmctdeploy
  template:
    metadata:
      labels:
        app: gsmctdeploy
    spec:
      containers:
      - name: gsmct-container
        image: dearsrini/gsmct:linux
        ports:
        - containerPort: 8080
